### ISSUE TITLE
`nativeBuilder` field should be visible

### ISSUE THREAD

**Issue by kevinherron** [hendraanggrian/javapoet-dsl#1]
I'm slowly converting some code to use this DSL and have found that I need access to the underlying `nativeBuilder` field to ease the transition.

For example, whilst in the middle of defining a type using the DSL, I need to define another inner type. The DSL offers these functions:
```
    override fun type(name: String, builder: (TypeSpecBuilder.() -> Unit)?) {
        nativeBuilder.addType(buildTypeSpec(name, builder))
    }

    override fun type(className: ClassName, builder: (TypeSpecBuilder.() -> Unit)?) {
        nativeBuilder.addType(buildTypeSpec(className, builder))
    }
```

but these require me to rewrite the code for the type I'm trying to add in the DSL as well. What I'd rather do in the meantime is something like:

```
nativeBuilder.addType(generateFooTypeSpec())
```

where `generateFooTypeSpec()` is a method that returns a JavaPoet `TypeSpec`.

**Comment by hendraanggrian** [comment]
I can see your point, `type(spec: TypeSpec)` should have been included in the first place. Also, I had a feeling `type(name: String, builder: (TypeSpecBuilder.() -> Unit)?)`, and `type(className: ClassName, builder: (TypeSpecBuilder.() -> Unit)?)` should return `TypeSpec`, might be useful to some.

**Comment by kevinherron** [comment]
Yes, `type(spec: TypeSpec)` would work as well.

I don't need currently need a `TypeSpec` returned by these functions but it's possible someone else might. I'm not sure what you would do with it because it will have already been added to the outer type. There's no harm in ignoring the return value though.

**Comment by hendraanggrian** [comment]
Version `0.3-rc1` is out specifically addressing this issue. I prefer support for these native specs than making `nativeBuilder` public, unless of course there is strong reason to do so.

**Comment by kevinherron** [comment]
Thanks 👍
