### ISSUE TITLE
Published source jars are empty

### ISSUE THREAD

**Issue by kevinherron** [hendraanggrian/javapoet-dsl#2]
The source jars you're publishing to jcenter are empty save for some package folders.

**Comment by kevinherron** [comment]
<img width="882" alt="Screen Shot 2019-06-11 at 2 00 33 PM" src="https://user-images.githubusercontent.com/340273/59306519-49359a00-8c51-11e9-89da-bfc5fd1c5e60.png">

**Comment by hendraanggrian** [comment]
Thanks for pointing it out, I might have been uploading to jcenter the wrong way all these time. My immediate reaction is that it is related to [an issue](https://github.com/novoda/bintray-release/issues/262) from [bintray-release](https://github.com/novoda/bintray-release). I'll try to contribute for a fix (or abandon this plugin altogether if I can't) and will update when I have more information.

**Comment by kevinherron** [comment]
If you don't mind I can submit a PR with all the pieces you're missing to publish properly to Sonatype OSS / Maven Central.

You'll need to create a Sonatype account and register your group name to do the publishing under though.

**Comment by hendraanggrian** [comment]
I appreciate the help, but I've always been uploading to jcenter and removing all my artifacts to OSS/Maven Central might take some time.

However, version 0.3-rc2 is out with correct sources jar. Javadoc jar is still empty though, I think it's related to [this issue](https://github.com/Kotlin/dokka/issues/42). Keep in mind that 0.3-rc2 is a rather large update, substantial amount of refactoring may be needed.

**Comment by kevinherron** [comment]
@hendraanggrian in rc2 it seems you can only construct, e.g. a TypeSpec, while in the scope of a TypeContainer, of which the only implementation seems to be a JavaFileBuilder.

This means I can't just independently build a TypeSpec without being inside a JavaFile construct right now, which seems like a step backwards.

**Comment by hendraanggrian** [comment]
I've come to realize it might be important to create these specs independently. So in rc3, specs (e.g. TypeSpec) and their builder classes can be modified using `invoke` operator:

```kotlin
import com.hendraanggrian.javapoet.invoke

val myType = (TypeSpec.classBuilder("MyClass")) {
    ...
}

val myOtherType = myType {
    ...
}
```

The effectiveness of these operator functions compared to full-on dedicated top-level functions (e.g. `buildTypeSpec`), however, is debatable.
